# Generated by Django 4.0.10 on 2023-03-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_realtor',
        ),
    ]
