# Generated by Django 4.1.7 on 2023-02-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_kind', models.CharField(choices=[('원룸', '원룸'), ('투룸', '투룸'), ('쓰리룸', '쓰리룸'), ('오피스텔', '오피스텔'), ('아파트', '아파트')], max_length=20)),
                ('cell_kind', models.CharField(choices=[('월세', '월세'), ('매매', '매매')], max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('visited', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
