# Generated by Django 4.1.7 on 2023-03-06 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dong_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gu_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('room', models.PositiveIntegerField(blank=True, null=True)),
                ('toilet', models.PositiveIntegerField(blank=True, null=True)),
                ('pyeongsu', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_to_station', models.PositiveIntegerField(blank=True, null=True)),
                ('room_kind', models.CharField(choices=[('원룸', '원룸'), ('투룸', '투룸'), ('쓰리룸', '쓰리룸'), ('오피스텔', '오피스텔'), ('아파트', '아파트')], max_length=20)),
                ('cell_kind', models.CharField(choices=[('월세', '월세'), ('전세', '전세'), ('매매', '매매'), ('상관없음', '상관없음')], max_length=20)),
                ('dong', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.URLField(blank=True, null=True)),
                ('station_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('visited', models.PositiveIntegerField(default=0, editable=False)),
                ('gu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.gu_list')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
