# Generated by Django 4.1.7 on 2023-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="is_sale",
            field=models.BooleanField(default=True),
        ),
    ]
