# Generated by Django 4.1.7 on 2023-03-07 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gu_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="house",
            name="station_distance",
        ),
        migrations.AddField(
            model_name="house",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="realtor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="realtor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="cell_kind",
            field=models.CharField(
                choices=[("월세", "월세"), ("전세", "전세"), ("매매", "매매")], max_length=20
            ),
        ),
        migrations.CreateModel(
            name="Dong_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "gu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dong",
                        to="houses.gu_list",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="house",
            name="dong",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="houses.dong_list",
            ),
            preserve_default=False,
        ),
    ]
