# Generated by Django 4.1.7 on 2023-03-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': []},
        ),
    ]
