# Generated by Django 4.0.10 on 2023-03-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='photo',
        ),
    ]
