# Generated by Django 4.1.7 on 2023-03-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_alter_house_is_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="cell_kind",
            field=models.CharField(
                choices=[("MONTHLY_RENT", "월세"), ("CHARTER", "전세"), ("SALE", "매매")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="room_kind",
            field=models.CharField(
                choices=[
                    ("ONE_ROOM", "원룸"),
                    ("TWO_ROOM", "투룸"),
                    ("THREE_ROOM", "쓰리룸 이상"),
                    ("OFFICETEL", "오피스텔"),
                    ("APART", "아파트"),
                ],
                max_length=20,
            ),
        ),
    ]
