# Generated by Django 4.0.10 on 2023-03-16 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keyword',
            new_name='options',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='is_owner',
            new_name='is_host',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='house',
            name='realtor',
        ),
        migrations.AddField(
            model_name='house',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
    ]
