# Generated by Django 4.1.7 on 2023-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='price',
            new_name='deposit',
        ),
        migrations.AddField(
            model_name='house',
            name='maintenanc_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='monthly_rent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='sale',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='cell_kind',
            field=models.CharField(choices=[('SALE', '매매'), ('CHARTER', '전세'), ('MONTHLY_RENT', '월세')], max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='room_kind',
            field=models.CharField(choices=[('ONE_ROOM', '원룸'), ('HOME', '주택'), ('APART', '아파트'), ('VILLA', '빌라'), ('OFFICETEL', '오피스텔'), ('SHARE_HOUSE', '쉐어하우스')], max_length=20),
        ),
    ]
