# Generated by Django 4.1.7 on 2023-03-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.dong_list'),
        ),
    ]
