# Generated by Django 4.1.7 on 2023-03-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={},
        ),
    ]
