# Generated by Django 4.1.7 on 2023-03-08 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0002_gu_list_remove_house_station_distance_house_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='distance_to_station',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='pyeongsu',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='room',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='toilet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
