# Generated by Django 4.1.7 on 2023-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="house",
            name="cell_kind",
            field=models.CharField(choices=[("월세", "월세"), ("매매", "매매")], max_length=20),
        ),
        migrations.AlterField(
            model_name="house",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="house",
            name="room_kind",
            field=models.CharField(
                choices=[
                    ("원룸", "원룸"),
                    ("투룸", "투룸"),
                    ("쓰리룸", "쓰리룸"),
                    ("오피스텔", "오피스텔"),
                    ("아파트", "아파트"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="visited",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
