# Generated by Django 4.1.7 on 2023-03-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_rename_price_house_deposit_house_maintenanc_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='maintenanc_cost',
            new_name='maintenance_cost',
        ),
    ]
