# Generated by Django 4.1.7 on 2023-03-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_house_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='owner',
        ),
    ]
