# Generated by Django 4.1.7 on 2023-03-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_house_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='photo',
        ),
    ]
