# Generated by Django 4.1.4 on 2023-03-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_keyword_house_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='cell_kind',
            field=models.CharField(choices=[('월세', '월세'), ('전세', '전세'), ('매매', '매매')], max_length=20),
        ),
    ]
