# Generated by Django 4.0.10 on 2023-03-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_safetyoptions_rename_name_options_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='cell_kind',
            new_name='sell_kind',
        ),
    ]
