# Generated by Django 4.1.7 on 2023-03-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_remove_house_dong'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='dong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.dong_list'),
        ),
    ]
