# Generated by Django 4.1.7 on 2023-03-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_rename_maintenanc_cost_house_maintenance_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
    ]
