# Generated by Django 4.1.4 on 2023-03-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_photo_house_price_alter_house_cell_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='station_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
