# Generated by Django 4.1.7 on 2023-03-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_house_dong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='station_distance',
        ),
    ]
