# Generated by Django 4.1.7 on 2023-03-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_house_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
