# Generated by Django 4.1.7 on 2023-03-07 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_remove_house_station_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='gu',
        ),
        migrations.AlterField(
            model_name='dong_list',
            name='gu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dong', to='houses.gu_list'),
        ),
        migrations.AlterField(
            model_name='house',
            name='dong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.dong_list'),
        ),
    ]
