# Generated by Django 4.1.7 on 2023-03-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_keyword_remove_house_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cell_kind',
            field=models.CharField(choices=[('월세', '월세'), ('전세', '전세'), ('매매', '매매'), ('상관없음', '상관없음')], max_length=20),
        ),
    ]
