# Generated by Django 4.0.10 on 2023-03-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_alter_house_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='is_host',
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
