# Generated by Django 4.1.7 on 2023-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_alter_house_cell_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='dong',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='gu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
