# Generated by Django 4.0.10 on 2023-03-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_remove_house_is_host_alter_house_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
