# Generated by Django 4.1.4 on 2023-03-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_dong_gu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dong',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dong',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gu',
            name='updated_at',
        ),
    ]
