# Generated by Django 4.0.10 on 2023-03-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_house_is_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='is_like',
        ),
    ]
