# Generated by Django 4.1.7 on 2023-03-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_remove_dong_created_at_remove_dong_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dong',
            old_name='dong',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gu',
            old_name='gu',
            new_name='name',
        ),
        migrations.AddField(
            model_name='dong',
            name='gu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='houses.gu'),
            preserve_default=False,
        ),
    ]
