# Generated by Django 4.1.7 on 2023-03-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_rename_dong_dong_name_rename_gu_gu_name_dong_gu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dong',
            new_name='Dong_list',
        ),
        migrations.RenameModel(
            old_name='Gu',
            new_name='Gu_list',
        ),
    ]
