# Generated by Django 4.0.10 on 2023-03-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_rename_options_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Safetyoption',
            field=models.ManyToManyField(to='houses.safetyoption'),
        ),
        migrations.AddField(
            model_name='house',
            name='option',
            field=models.ManyToManyField(to='houses.option'),
        ),
    ]
