# Generated by Django 4.0.10 on 2023-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_house_safetyoption_house_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='house',
            name='Safetyoption',
            field=models.ManyToManyField(related_name='safetyoption', to='houses.safetyoption'),
        ),
    ]
