<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-11 15:17
=======
# Generated by Django 4.1.7 on 2023-03-11 08:37
>>>>>>> bc7f905282b6a44727561ad7230f9aa804254b10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ("houses", "0001_initial"),
=======
        ('houses', '0001_initial'),
>>>>>>> bc7f905282b6a44727561ad7230f9aa804254b10
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Image",
                        to="houses.house",
                    ),
                ),
            ],
            options={
                "abstract": False,
=======
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='houses.house')),
            ],
            options={
                'abstract': False,
>>>>>>> bc7f905282b6a44727561ad7230f9aa804254b10
            },
        ),
    ]
