# Generated by Django 4.1.7 on 2023-03-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_house_rating_review_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='house_rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=5),
        ),
    ]
