# Generated by Django 4.1.7 on 2023-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_alter_house_address_alter_house_cell_kind_and_more"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="house",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="house",
            field=models.ManyToManyField(related_name="wishlist", to="houses.house"),
        ),
    ]
