# Generated by Django 4.1.4 on 2023-03-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
