<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-11 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.1.7 on 2023-03-11 08:37

from django.db import migrations, models
>>>>>>> bc7f905282b6a44727561ad7230f9aa804254b10


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("houses", "0001_initial"),
=======
>>>>>>> bc7f905282b6a44727561ad7230f9aa804254b10
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="HouseList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recently_views", models.ManyToManyField(to="houses.house")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
=======
            name='HouseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
>>>>>>> bc7f905282b6a44727561ad7230f9aa804254b10
            },
        ),
    ]
