# Generated by Django 4.1.7 on 2023-03-13 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0003_alter_house_options'),
        ('houselists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselist',
            name='recently_views',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_list', to='houses.house'),
        ),
        migrations.AlterField(
            model_name='houselist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
