# Generated by Django 4.0.10 on 2023-03-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houselists', '0001_initial'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselist',
            name='recently_views',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_list', to='houses.house'),
        ),
    ]
