# Generated by Django 4.1.7 on 2023-03-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houselists', '0003_houselist_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselist',
            name='add_time',
        ),
    ]
