# Generated by Django 4.1.7 on 2023-03-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houselists', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
