# Generated by Django 4.1.7 on 2023-03-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houselists', '0004_alter_houselist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
