# Generated by Django 4.0.10 on 2023-03-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_house_photo'),
        ('chatRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatRoom', to='houses.house'),
            preserve_default=False,
        ),
    ]
